### ISSUE TITLE
Does it work on board computer(Jetson) or External PC connected to on-board computer ?

### ISSUE THREAD

**Issue by ryouta-777** [Sayantani-Bhattacharya/unitree_go2_nav#4]
Hi, author 

Firstly I appreciate you this great job.
Does it work on board computer(Jetson) or External PC connected to on-board computer ?
I'm afraid my question is very primitive.

Thanks,

**Comment by Sayantani-Bhattacharya** [comment]
Hi, yes it should work on Jetson ( set it up with ROS 2 Jazzy, you can consider using a docker container also). I used my Ubuntu Laptop because of time constraints, and connected go2 via Ethernet.

**Comment by ryouta-777** [comment]
Hi, 
Thank you for your reply.  As far as I know, On-board computer (Jetson) is ROS2 foxy as default.  Can it work based on ROS2 foxy?  Or had I better use docker image of Ubuntu & ROS2 Jazzy on Jetson ?

Thanks,

**Comment by Sayantani-Bhattacharya** [comment]
You could try building ros package from source, I made that work for Humble on Jetson Orin Nano, you can try with Jazzy as well. Docker is always an option in case this does not work.

**Comment by ryouta-777** [comment]
Thank you. As you said, I try to build it on ROS2 humble. But I encountered the below error in "colcon build". ( fatal error: rmw/discovery_options.h: No such file or directory )
How did you solve it ?


$colcon build
Starting >>> unitree_go2_nav_interfaces
Starting >>> cyclonedds
Starting >>> unitree_api
Starting >>> unitree_go
Starting >>> unitree_hg
Starting >>> go2_description
Finished <<< go2_description [0.10s]                                                                                                                                         
Finished <<< cyclonedds [0.30s]                                                                                                                                                
Starting >>> rmw_cyclonedds_cpp
Finished <<< unitree_hg [0.44s]                                                                                                                                             
Finished <<< unitree_api [0.45s]
--- stderr: rmw_cyclonedds_cpp
/home/rk001/saya_go2_nav/src/unitree_go2_nav/unitree_ros2/unitree_ros2/cyclonedds_ws/src/rmw_cyclonedds/rmw_cyclonedds_cpp/src/rmw_node.cpp:45:10: fatal error: rmw/discovery_options.h: No such file or directory
   45 | #include "rmw/discovery_options.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/rmw_cyclonedds_cpp.dir/build.make:90: CMakeFiles/rmw_cyclonedds_cpp.dir/src/rmw_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/rmw_cyclonedds_cpp.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< rmw_cyclonedds_cpp [0.15s, exited with code 2]
Aborted  <<< unitree_go [0.45s]
Aborted  <<< unitree_go2_nav_interfaces [0.47s]

Summary: 4 packages finished [0.69s]
  1 package failed: rmw_cyclonedds_cpp
  2 packages aborted: unitree_go unitree_go2_nav_interfaces
  1 package had stderr output: rmw_cyclonedds_cpp
  2 packages not processed

**Comment by Sayantani-Bhattacharya** [comment]
Yaa, u need to first build the cyclonedds in isolation [--packages-select] and then do colcon build. Also source ros humble before colcon build.
Follow the instruction here: https://github.com/unitreerobotics/unitree_ros2

**Comment by ryouta-777** [comment]
Hi, 
I keep trying your repo.
I faced the below error after cyclonedds build in isolation and whole colcon build.
It is done under docker container of Ubuntu 22.04, ROS2 hunble on Jetson.
root@ubuntu:~/ros2_ws/src/unitree_go2_nav# source install/setup.bash
not found: "/root/ros2_ws/src/unitree_go2_nav/install/rmw_cyclonedds_cpp/share/rmw_cyclonedds_cpp/local_setup.bash"

**Comment by Sayantani-Bhattacharya** [comment]
Run pwd on local_setup.bash, and try sourcing from that location.

**Comment by 16stelter** [comment]
Hello, maybe to add a question to this issue: How is the package meant to be used? Should we build this package on an external computer and connect it to the robot or should we build this directly on the robot? Also, if we build it on jazzy and the robot runs on foxy, wouldn't that still cause issues with cyclonedds?

It looks like a really cool package, but I don't understand how to use it correctly.

**Comment by ryouta-777** [comment]
Hi, Author
I appreciate your supports truly.
I think rmw_cyclonedds folder is not needed in humble environment. Because the below commands have been done.
$ sudo apt install ros-humble-rmw-cyclonedds-cpp
$ sudo apt install ros-humble-rosidl-generator-dds-idl

Maybe I've paved the way to solve this build-error trouble.
I confirmed topics included actual data by command $ros2 topic echo [topic].
I think bring up of Go2 could be done correctly.

**Comment by Sayantani-Bhattacharya** [comment]
@16stelter Hi, This was made as an external compute connected via Ethernet to go2. I didn't see any apparent network issues with this setup, frame rate and pub frequencies were pretty good. But that being said there can be better ways to do it as well.

**Comment by 16stelter** [comment]
I see, thank you! And you've been running Foxy on the robot and Jazzy on the external computer? Just trying to figure out what's causing the issues on my end.

**Comment by Sayantani-Bhattacharya** [comment]
I tried with both humble and jazzy, and GO2 topics were discoverable from both. I am not sure which Distro the go2 SDK was on though... Are you facing some issues with that?

**Comment by 16stelter** [comment]
Thanks! Yes, I am facing some issues with that, I've submitted a separate issue with more details.

**Comment by ryouta-777** [comment]
All problems seem to be resolved. I close this issue.
